name: Fill GitHub Contributions

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  fill-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "M SRAVANTHI"
          git config user.email "sravanthim674@gmail.com"

      - name: Make multiple commits
        run: |
          FILE=dummy.txt
          # Create 5 commits with slightly different timestamps to make dark green blocks
          for i in {1..5}; do
            DATE=$(date -d "-$i hour" '+%Y-%m-%d %H:%M:%S')
            echo "Commit for $DATE" >> $FILE
            git add $FILE
            git commit -m "Commit for $DATE" --date "$DATE"
          done

      - name: Push commits
        run: git push
