name: Fill GitHub Contributions

on:
  schedule:
    # Runs every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  fill-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Make a dummy commit
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Commit for $DATE" >> dummy.txt
          git add dummy.txt
          git commit -m "Commit for $DATE"

      - name: Push commit
        run: git push
